name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
permissions:
  contents: read 
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-gh-pages@v4
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          build_dir: dist
          clean: true 

